### ISSUE TITLE
Project Stage 2 Checklist (private)

### ISSUE THREAD

**Issue by MickAlmighty** [MickAlmighty/TUM#4]
# Stage 2 Checklist

- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [x] layers are clearly stated using language terms only
- [ ] `Data` API is abstract and contains object model representing process data
- [ ] prove that the data integration is implemented.
- [ ] `Logic` uses only the abstract `Data` layer API
- [x] Communication between the client and the server should be made using the `Web Socket`
- [x] reactive and interactive communication are used
- [x] Unit Test - layers are tested independently using abstract API
- [x] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purpose (expected but not required)
